language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  only:
    - master

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/deepomatic_cli-*.whl
  - pip install pytest==4.3.0

# command to run tests
script:
  - pytest
