language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  only:
    - master

# command to install dependencies
install:
  - pip install -r requirements.dev.txt
  - pip install -e .

# command to run tests
script:
  # linter
  - flake8 --statistics --verbose
  # unit tests
  - pytest -vv
  # package build test
  - python setup.py bdist_wheel
  # package install test
  - pip install dist/deepomatic_cli-*.whl
